#%RAML 1.0 NamedExample
  [
    {
      "employeeId": 6,
      "employeeName" : "Aishwarya Reddy",
      "employeeContact": "91-4321098765",
      "employeeAddress": "890, Jubilee Hills, Hyderabad, India"
    },
    {
      "employeeId": 7,
      "employeeName" : "Aishwarya Rai",
      "employeeContact": "91-7365098765",
      "employeeAddress": "910, Airoli, Navi Mumbai, Maharashtra, India"
    }
  ]