#%RAML 1.0 NamedExample

{
  "personId": 3,
  "personName": "Rajesh Gupta",
  "personAadhar": "1234 5678 9012",
  "personContact": "91-9876543210",
  "personAddress": "123, Main Street, New Delhi, India",
  "personZipcode": 110001
}
