http:
  host: "localhost"
  port: "8081"
  
database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  databaseName: "FinalAssessment"
  
file:
  "directory": C:\Users\G68\OneDrive - Capgemini\Desktop\POC
  