#%RAML 1.0
title: Person-data-PAPI

types:
  PersonFullData: !include dataTypes/personNewType.raml
  Employee: !include dataTypes/employeeType.raml

/person-data-papi: 
  post:
    description: Push data to the employee database
    body:
      application/json:
        type: Employee[]
        example: !include examples/employeePostData.raml
    responses:
      201:
        body:
          application/json:
            example:
              {
                "message": "Employees created successfully"
              }
  
  /{name}:
    get:
      description: Retrieve data from the employee and person database
      responses:
        200:
          body:
            application/json:
              type: PersonFullData
              example: !include examples/personNewData.raml